const PHOTOS = {
  "au-d1-opera": ["Bernard Spragg · CC0", "Sydney_Australia._(21339175489).jpg"],
  "au-d1-tour": ["Nick-D · CC BY-SA 3.0", "Sydney_Opera_House_concert_hall_October_2018.jpg"],
  "au-d1-chair": ["Mitch Ames · CC BY-SA 3.0", "Mrs_Macquarie%27s_Chair_2013.jpg"],
  "au-d2-nielsen": ["Peter Woodard · CC0", "Nielsen_Park_Port_Jackson.JPG"],
  "au-d2-parsley": ["-wuppertaler · CC BY 4.0", "AUS_Sydney,_Woollahra,_Parsley_Bay_Bridge_005.jpg"],
  "au-d2-gap": ["Dietmar Rabich · CC BY-SA 4.0", "Sydney_(AU),_Watsons_Bay_--_2019_--_2295.jpg"],
  "au-d3-manly": ["J Bar · CC BY-SA 3.0", "Shelly_Beach_Manly.JPG"],
  "au-d3-northhead": ["ColonelLight · CC0", "Burragula_Lookout_North_Head_02.jpg"],
  "au-d4-lagoon": ["Niki Gango · CC BY-SA 3.0", "Airlie_Beach_Lagoon.JPG"],
  "au-d5-sand": ["Slug69 · CC BY-SA 2.0", "Whitehaven_Beach,_Whitsunday_Island,_Queensland.jpg"],
  "au-d5-hill": ["Isderion · CC BY-SA 3.0 DE", "Hill_Inlet_at_the_end_of_Whitehaven_Beach_in_the_Whitsundays.JPG"],
  "au-d6-town": ["Richard N Horne · CC BY 4.0", "Airlie_Beach_is_a_departure_point_for_the_Great_Barrier_Reef.jpg"],
  "au-d7-lanes": ["Ashton 29 · CC BY-SA 4.0", "Melbourne_laneway.jpg"],
  "au-d8-reb": ["Diliff, Ian Fieggen · CC BY 2.5", "Royal_exhibition_building_tulips_straight.jpg"],
  "au-d8-fitzroy": ["Nick-D · CC BY-SA 4.0", "Buildings_on_Gertrude_Street_December_2020.jpg"],
  "au-d8-convent": ["Redtree21 · CC BY-SA 4.0", "Abbotsford_Convent_Looking_North.jpg"],
  "au-d8-ngv": ["Shkuru Afshar · CC BY-SA 4.0", "National_Gallery_of_Victoria_2024.jpg"]
};

function photo(id) {
  const [credit, file] = PHOTOS[id];
  return { src: `photos/${id}.jpg`, credit, link: `https://commons.wikimedia.org/wiki/File:${file}` };
}

window.SEED_TRIPS = [
  {
    id: "australia-2027",
    title: "澳洲",
    start: "2027-04-28",
    end: "2027-05-05",
    summary: "按开口程排：4月28日进悉尼，5月1日飞圣灵群岛，5月4日飞墨尔本，5月5日从墨尔本离开。这几天三个州都在上学，没有学校假期。要注意的是5月3日是昆士兰劳动节，5月1日到3日是艾尔利的长周末，酒店和船先订。景点挑的是本地人推荐、人比经典打卡点少的地方：悉尼不走邦迪到库吉，改走海港东岸；墨尔本不去 Hosier Lane 和圣基尔达，改去 Carlton、Fitzroy 和 Abbotsford。",
    days: [
      {
        id: "au-d1",
        date: "2027-04-28",
        city: "悉尼",
        title: "下飞机，只在港边走",
        items: [
          {
            id: "au-d1-opal",
            time: "落地后",
            kind: "transport",
            name: "机场站坐火车到环形码头",
            address: "Sydney Airport International Station",
            lat: -33.9344,
            lng: 151.1652,
            reservation: "none",
            reservationNote: "不用订票。刷银行卡或 Opal 卡即可。",
            bookingUrl: "",
            note: "国际航站楼和国内航站楼是两个火车站。坐 T8，方向进城，经过中央车站、市政厅、温亚德，到环形码头下。机场站另收一笔通行费，比普通地铁贵。行李多、很累就打车，大约三四十分钟到环形码头。"
          },
          {
            id: "au-d1-stay",
            time: "入住",
            kind: "stay",
            name: "住环形码头或岩石区",
            address: "Circular Quay, Sydney",
            lat: -33.8612,
            lng: 151.2108,
            reservation: "required",
            reservationNote: "港边酒店位置好的先满，三晚一起订。",
            bookingUrl: "https://www.booking.com/searchresults.html?ss=Circular+Quay%2C+Sydney&checkin=2027-04-28&checkout=2027-05-01",
            note: "住这儿，歌剧院、岩石区和渡轮码头都能走路到。后两天都从环形码头坐渡轮出发。5月1日早上再去机场。"
          },
          {
            id: "au-d1-opera",
            time: "下午",
            kind: "sight",
            name: "悉尼歌剧院外面",
            address: "Bennelong Point, Sydney NSW",
            lat: -33.8568,
            lng: 151.2153,
            reservation: "none",
            reservationNote: "只在室外走，不用票。",
            bookingUrl: "",
            why: "第一天有时差，这里走路就到，不用转车。外面看不要票。",
            photo: photo("au-d1-opera"),
            note: "从环形码头沿着海走过去。先看壳，再绕到海岬一侧。刚下飞机不要排室内导览。"
          },
          {
            id: "au-d1-tour",
            time: "想进去再订",
            kind: "sight",
            name: "歌剧院室内导览",
            address: "Sydney Opera House Welcome Centre",
            lat: -33.8568,
            lng: 151.2153,
            reservation: "recommended",
            reservationNote: "官网写明建议提前买。每场大约35人，迟到超过5分钟票作废。",
            bookingUrl: "https://www.sydneyoperahouse.com/tours/sydney-opera-house-tour",
            why: "只有想看音乐厅内部才去。每场限人数，里面不挤。",
            photo: photo("au-d1-tour"),
            note: "到了再决定。订的话选下午场，提前15分钟到下层的 Welcome Centre。不订也不影响这天。"
          },
          {
            id: "au-d1-chair",
            time: "傍晚",
            kind: "sight",
            name: "皇家植物园到麦考利夫人椅子",
            address: "Mrs Macquaries Point, Sydney",
            lat: -33.8599,
            lng: 151.2226,
            reservation: "none",
            reservationNote: "植物园免费，不用订。",
            bookingUrl: "",
            why: "歌剧院和大桥同框的位置，傍晚比环形码头人少。",
            photo: photo("au-d1-chair"),
            note: "从歌剧院继续往东走进植物园，顺着海走到尽头，就是看歌剧院和港湾的那个石头椅子。原路走回岩石区。"
          },
          {
            id: "au-d1-bar",
            time: "晚饭",
            kind: "food",
            name: "Opera Bar",
            address: "Lower Concourse, Sydney Opera House",
            lat: -33.8583,
            lng: 151.2142,
            reservation: "none",
            reservationNote: "歌剧院下层的酒吧餐厅，现场坐，不接受预订。",
            bookingUrl: "",
            note: "就在歌剧院脚下。要靠窗的位置就早点去。这天别再跑别的区。"
          }
        ]
      },
      {
        id: "au-d2",
        date: "2027-04-29",
        city: "悉尼",
        title: "海港东岸：玫瑰湾走到沃森斯湾",
        items: [
          {
            id: "au-d2-ferry",
            time: "10:00",
            kind: "transport",
            name: "F9 渡轮到玫瑰湾",
            address: "Circular Quay Wharf 2",
            lat: -33.8612,
            lng: 151.2108,
            reservation: "none",
            reservationNote: "刷 Opal 或银行卡，不用提前买。",
            bookingUrl: "",
            note: "环形码头 2 号码头，看牌子 F9 Watsons Bay。坐到 Rose Bay 下，大约 12 分钟。"
          },
          {
            id: "au-d2-nielsen",
            time: "10:30",
            kind: "sight",
            name: "隐士步道到尼尔森公园",
            address: "Hermitage Foreshore Track, Vaucluse",
            lat: -33.8505,
            lng: 151.268,
            reservation: "none",
            reservationNote: "国家公园步道，不用票。",
            bookingUrl: "",
            why: "本地人推荐的海港步道，平路，回头就是大桥和歌剧院。比邦迪到库吉人少很多。",
            photo: photo("au-d2-nielsen"),
            note: "下船沿 New South Head Road 往北走，左转 Tivoli Avenue，再左转 Bay View Hill Road，看牌子 Hermitage Foreshore 进步道。从码头到尼尔森公园大约一个半小时，路上经过几个小沙湾。终点的沙滩叫 Shark Beach，有防鲨网，可以下水。"
          },
          {
            id: "au-d2-lunch",
            time: "12:30",
            kind: "food",
            name: "The Nielsen",
            address: "Nielsen Park, Greycliffe Avenue, Vaucluse",
            lat: -33.8508,
            lng: 151.2683,
            reservation: "none",
            reservationNote: "公园里的咖啡馆，现场点。",
            bookingUrl: "",
            note: "就在 Shark Beach 后面。吃完可以在草地上坐一会儿再走。"
          },
          {
            id: "au-d2-parsley",
            time: "13:30",
            kind: "sight",
            name: "帕斯利湾吊桥",
            address: "Parsley Bay Reserve, Vaucluse",
            lat: -33.8496,
            lng: 151.2777,
            reservation: "none",
            reservationNote: "公共公园，不用票。",
            bookingUrl: "",
            why: "顺路的小吊桥和雨林小沟，走过去只多十分钟。",
            photo: photo("au-d2-parsley"),
            note: "从尼尔森公园沿 Coolong Road 走到 Wentworth Road，右转 Fitzwilliam Road，在 43a 号旁边的小路进去就是吊桥。过桥后顺 The Crescent 往下走，一直到沃森斯湾。尼尔森公园到沃森斯湾不进 Vaucluse House 的话，大约一个半小时。"
          },
          {
            id: "au-d2-gap",
            time: "15:00",
            kind: "sight",
            name: "沃森斯湾和 The Gap 悬崖",
            address: "Gap Park, Watsons Bay",
            lat: -33.8452,
            lng: 151.287,
            reservation: "none",
            reservationNote: "不用票。",
            bookingUrl: "",
            why: "港湾这边是小渔村，翻过小坡就是外海悬崖。终点有渡轮直接回城，不用坐车。",
            photo: photo("au-d2-gap"),
            note: "到了沃森斯湾先穿过码头对面的草地，走上 Gap Park，看外海那一侧的悬崖，来回二十分钟。天还亮、腿还有劲，可以再走去 Hornby 灯塔，来回多 3 公里左右。傍晚五点多天黑，四点半前往回走。"
          },
          {
            id: "au-d2-back",
            time: "16:30",
            kind: "transport",
            name: "沃森斯湾坐渡轮回环形码头",
            address: "Watsons Bay Wharf",
            lat: -33.8443,
            lng: 151.2817,
            reservation: "none",
            reservationNote: "不用订。",
            bookingUrl: "",
            note: "还是 F9，不到 20 分钟回到环形码头。这条船有时一小时才一班，到码头先看下一班时间，在旁边的海边草地等。"
          }
        ]
      },
      {
        id: "au-d3",
        date: "2027-04-30",
        city: "悉尼",
        title: "渡轮去曼利，往北角走",
        items: [
          {
            id: "au-d3-ferry",
            time: "10:00",
            kind: "transport",
            name: "F1 渡轮到曼利",
            address: "Circular Quay Wharf 3",
            lat: -33.8612,
            lng: 151.2108,
            reservation: "none",
            reservationNote: "刷 Opal 或银行卡，不用提前买。",
            bookingUrl: "",
            note: "环形码头看牌子 F1 Manly，一般在 3 号码头。船大约 30 分钟。坐船头或上层的外侧，这段是最好看的海港风景。风大，外套带着。"
          },
          {
            id: "au-d3-manly",
            time: "10:40",
            kind: "sight",
            name: "曼利海滩到 Shelly Beach",
            address: "Shelly Beach, Manly",
            lat: -33.8003,
            lng: 151.2975,
            reservation: "none",
            reservationNote: "不用票。",
            bookingUrl: "",
            why: "曼利主滩人多，不停留。Shelly Beach 是朝北的小湾，水平静。",
            photo: photo("au-d3-manly"),
            note: "下船穿过 The Corso 商业街，在这条街上买好午饭和水带走，北角上面没有店。到海滩右转，沿海边步道走大约 1 公里到 Shelly Beach。"
          },
          {
            id: "au-d3-northhead",
            time: "11:30",
            kind: "sight",
            name: "北角 Fairfax 观景台",
            address: "Fairfax Lookout, North Head Scenic Drive, Manly",
            lat: -33.8167,
            lng: 151.2963,
            reservation: "none",
            reservationNote: "国家公园，不用票。",
            bookingUrl: "",
            why: "站在悬崖上看整个悉尼港口和外海，5月开始有机会看到鲸鱼。来的人比曼利海滩少得多。",
            photo: photo("au-d3-northhead"),
            note: "从 Shelly Beach 停车场后面的步道往上爬，大约 80 米高，这是唯一累的一段。上去以后看牌子 Fairfax Lookout，在观景台附近吃带上来的午饭。从曼利码头算起单程大约 5 公里，两到三小时。出发前看一眼国家公园网站有没有封路通知。南边没有厕所，在曼利海滩上厕所、装水。"
          },
          {
            id: "au-d3-bus",
            time: "14:30",
            kind: "transport",
            name: "161 路回曼利码头",
            address: "North Fort, North Head Scenic Drive",
            lat: -33.8133,
            lng: 151.2925,
            reservation: "none",
            reservationNote: "公交车，刷卡上车。",
            bookingUrl: "",
            note: "North Fort 停车场坐 161 回曼利码头，工作日大约半小时一班，以 Transport NSW 的时刻为准。不想等车就原路走回去，下坡为主，大约 3 公里。"
          },
          {
            id: "au-d3-back",
            time: "15:30",
            kind: "transport",
            name: "渡轮回环形码头",
            address: "Manly Wharf",
            lat: -33.8001,
            lng: 151.284,
            reservation: "none",
            reservationNote: "不用订。",
            bookingUrl: "",
            note: "原船回去。今天不再加景点，晚上收拾行李，明天早上飞。"
          }
        ]
      },
      {
        id: "au-d4",
        date: "2027-05-01",
        city: "圣灵群岛",
        title: "飞艾尔利海滩",
        items: [
          {
            id: "au-d4-flight",
            time: "早上",
            kind: "transport",
            name: "悉尼飞普罗瑟派恩",
            address: "Whitsunday Coast Airport PPP",
            lat: -20.495,
            lng: 148.552,
            reservation: "required",
            reservationNote: "这天是昆士兰长周末的第一天，飞机会比平时满。目标是中午前后落地，不要订下午太晚的。",
            bookingUrl: "https://www.google.com/travel/flights?hl=zh-CN&q=One%20way%20flights%20from%20Sydney%20to%20Proserpine%20on%20May%201%202027",
            note: "机场代码 PPP，也叫 Whitsunday Coast。飞行大约两个半小时。汉密尔顿岛机场（HTI）更靠近海岛，但怀特黑文的船大多从艾尔利海滩开，所以飞 PPP。悉尼国内航站楼出发。"
          },
          {
            id: "au-d4-shuttle",
            time: "落地后",
            kind: "transport",
            name: "机场班车到艾尔利海滩",
            address: "Airlie Beach",
            lat: -20.2676,
            lng: 148.7166,
            reservation: "recommended",
            reservationNote: "班车按航班接，提前订座位更稳。不订就在到达厅找柜台，可能要等下一班。",
            bookingUrl: "https://www.whitsundaytransit.com.au/",
            note: "路程大约 35 到 40 分钟。告诉司机酒店名字。打车也可以，几个人一起分摊更合适。"
          },
          {
            id: "au-d4-stay",
            time: "入住",
            kind: "stay",
            name: "住艾尔利海滩主街或码头",
            address: "Airlie Beach QLD",
            lat: -20.2682,
            lng: 148.7172,
            reservation: "required",
            reservationNote: "5月3日是昆士兰劳动节，这三晚正好是长周末，码头附近会先订满。",
            bookingUrl: "https://www.booking.com/searchresults.html?ss=Airlie+Beach&checkin=2027-05-01&checkout=2027-05-04",
            note: "优先住 Coral Sea Marina 或主街，第二天早上走去码头。不要住到普罗瑟派恩镇上。"
          },
          {
            id: "au-d4-lagoon",
            time: "下午",
            kind: "sight",
            name: "艾尔利泻湖",
            address: "Airlie Beach Lagoon",
            lat: -20.2692,
            lng: 148.7188,
            reservation: "none",
            reservationNote: "免费公共泻湖。",
            bookingUrl: "",
            why: "5月还是水母季，这是镇上不用穿防刺服就能下水的地方。",
            photo: photo("au-d4-lagoon"),
            note: "主街走到海边就看见。泻湖有防护，可以直接游。外海游泳要穿防刺服。晚饭在主街吃，长周末热门的馆子早点去。"
          }
        ]
      },
      {
        id: "au-d5",
        date: "2027-05-02",
        city: "圣灵群岛",
        title: "怀特黑文和希尔因莱特",
        items: [
          {
            id: "au-d5-raft",
            time: "早上集合",
            kind: "sight",
            name: "Ocean Rafting Northern Exposure",
            address: "Coral Sea Marina, Airlie Beach",
            lat: -20.267,
            lng: 148.7135,
            reservation: "required",
            reservationNote: "这是这趟最该先订的一项，而且这天是长周末的周日。只订「南端白沙滩半天」会看不到希尔因莱特观景台。",
            bookingUrl: "https://www.oceanrafting.com.au/",
            why: "小快艇，人少，跑得快。怀特黑文上午十点到下午两点是大船集中靠岸的时候，越早出发越清静。",
            note: "订 Northern Exposure：怀特黑文沙滩、希尔因莱特观景台，加浮潜。有两个出发时间就选早的那个。集合点以确认邮件为准，常见是 Coral Sea Marina，不要走到另一头的 Port of Airlie。提前半小时到。防刺服船上有。带泳衣、毛巾、一双能上岸的鞋。晕船药在开船前吃。大风他们会改期或换沙滩，看短信。"
          },
          {
            id: "au-d5-enid",
            time: "二选一",
            kind: "sight",
            name: "Lady Enid 小帆船（备选）",
            address: "Airlie Beach",
            lat: -20.2682,
            lng: 148.7172,
            reservation: "recommended",
            reservationNote: "不坐快艇就订这条。最多24人，只收成人。",
            bookingUrl: "https://www.australiancruisegroup.com.au/whitsundays/whitehaven-beach-cruises/10hr-lady-enid-whitehaven-beach-sail-snorkel-cruise",
            why: "1962 年的老木帆船，最多 24 人，比快艇慢但安静，也去希尔因莱特和怀特黑文。",
            note: "早上 8 点从艾尔利出发，全天大约九个半小时，含吃的和浮潜。怕颠、想慢慢玩选这条；想早回来休息选上面的快艇。两个只订一个。"
          },
          {
            id: "au-d5-hill",
            time: "船上",
            kind: "sight",
            name: "希尔因莱特观景台",
            address: "Hill Inlet Lookout, Whitsunday Island",
            lat: -20.2597,
            lng: 149.0378,
            reservation: "none",
            reservationNote: "含在船票里。确认你订的那条船会上这个观景台。",
            bookingUrl: "",
            why: "白沙和蓝水搅在一起的那张照片就是从这里拍的，只能从高处看。",
            photo: photo("au-d5-hill"),
            note: "大多数船停在 Tongue Bay，上岸走一段林间路和台阶到观景台。花纹好不好看取决于潮水，订船时问一句他们当天几点上观景台。穿船方要求的鞋。"
          },
          {
            id: "au-d5-sand",
            time: "船上",
            kind: "sight",
            name: "怀特黑文海滩",
            address: "Whitehaven Beach, Whitsunday Island",
            lat: -20.282,
            lng: 149.0375,
            reservation: "none",
            reservationNote: "不能自己去，已经含在船票里。",
            bookingUrl: "",
            why: "7 公里长的白沙滩，大船都停在南端，往北走一段人就少了。",
            photo: photo("au-d5-sand"),
            note: "岛上没有路，也没有店。沙子细，会粘鞋。不要把沙子带走，公园在管。回程晚饭回艾尔利主街，今天不要再加别的活动。"
          }
        ]
      },
      {
        id: "au-d6",
        date: "2027-05-03",
        city: "圣灵群岛",
        title: "劳动节，在镇上休息",
        items: [
          {
            id: "au-d6-town",
            time: "10:30",
            kind: "sight",
            name: "艾尔利主街和码头",
            address: "Airlie Beach Main Street",
            lat: -20.2676,
            lng: 148.7166,
            reservation: "none",
            reservationNote: "不用订。",
            bookingUrl: "",
            why: "前一天出海很累，这天又是昆士兰公共假日，不再排远的。",
            photo: photo("au-d6-town"),
            note: "睡够再出门。泻湖、主街、码头走一圈。今天是公共假日，有的馆子会加收假日附加费，营业时间也可能变短。晚饭早点吃，行李收好，第二天要去机场。"
          },
          {
            id: "au-d6-half",
            time: "可不去",
            kind: "sight",
            name: "半天浮潜",
            address: "Airlie Beach",
            lat: -20.267,
            lng: 148.7135,
            reservation: "recommended",
            reservationNote: "只有还想下海才订。订半天，不要再订一整天。",
            bookingUrl: "https://www.oceanrafting.com.au/",
            note: "如果昨天的船因为天气取消，用这一天补。补的话仍然订含希尔因莱特的那条，并且把5月4日的飞机改到下午。"
          }
        ]
      },
      {
        id: "au-d7",
        date: "2027-05-04",
        city: "墨尔本",
        title: "飞到墨尔本，傍晚走小巷",
        items: [
          {
            id: "au-d7-flight",
            time: "早上",
            kind: "transport",
            name: "普罗瑟派恩飞墨尔本",
            address: "Melbourne Airport",
            lat: -37.669,
            lng: 144.841,
            reservation: "required",
            reservationNote: "这条线经常要在布里斯班或悉尼转机，全程可能要五六个小时。先看时刻再订酒店。",
            bookingUrl: "https://www.google.com/travel/flights?hl=zh-CN&q=One%20way%20flights%20from%20Proserpine%20to%20Melbourne%20on%20May%204%202027",
            note: "早上从艾尔利返回 PPP，班车大约 40 分钟，再加安检，按飞机起飞前两小时到机场倒推。落地是墨尔本国内航站楼。"
          },
          {
            id: "au-d7-sky",
            time: "落地后",
            kind: "transport",
            name: "SkyBus 到南十字车站",
            address: "Southern Cross Station, Melbourne",
            lat: -37.8184,
            lng: 144.9525,
            reservation: "none",
            reservationNote: "车上或官网都能买，不用提前锁位。",
            bookingUrl: "https://www.skybus.com.au/",
            note: "墨尔本机场没有火车站。跟随 SkyBus 牌子，在航站楼外上车，终点南十字车站，大约 30 到 40 分钟，堵车会更久。市区交通刷 Myki 卡，机场大巴本身不是 Myki。"
          },
          {
            id: "au-d7-stay",
            time: "入住",
            kind: "stay",
            name: "住弗林德斯街或南十字附近",
            address: "Flinders Street, Melbourne",
            lat: -37.8183,
            lng: 144.9671,
            reservation: "required",
            reservationNote: "只住两晚，城中心方便坐电车。",
            bookingUrl: "https://www.booking.com/searchresults.html?ss=Flinders+Street+Melbourne&checkin=2027-05-04&checkout=2027-05-06",
            note: "如果 5 日晚上的国际航班，6 日清晨再退房也行。住这儿，明天坐电车和火车都方便。"
          },
          {
            id: "au-d7-lanes",
            time: "傍晚",
            kind: "sight",
            name: "Flinders Lane 一带的小巷",
            address: "Centre Place, Melbourne",
            lat: -37.816,
            lng: 144.9653,
            reservation: "none",
            reservationNote: "巷子免费。",
            bookingUrl: "",
            why: "本地人说 Hosier Lane 这几年又挤又乱。旁边这几条巷子一样有涂鸦和小店，傍晚人少一些。",
            photo: photo("au-d7-lanes"),
            note: "从弗林德斯街车站对面开始，先走 Degraves Street 和 Centre Place，再沿 Flinders Lane 往东走到 AC/DC Lane。整段走路二十分钟，最后正好到下面的晚饭。"
          },
          {
            id: "au-d7-coda",
            time: "晚饭",
            kind: "food",
            name: "Coda",
            address: "141 Flinders Lane, Melbourne VIC 3000",
            lat: -37.8162,
            lng: 144.9704,
            reservation: "recommended",
            reservationNote: "弗林德斯巷的小馆子，晚餐建议订。",
            bookingUrl: "https://www.opentable.com/r/coda-melbourne",
            note: "亚洲口味、分着吃。订 19:00 左右。如果飞机晚点，取消预订，在巷子口随便吃。"
          }
        ]
      },
      {
        id: "au-d8",
        date: "2027-05-05",
        city: "墨尔本",
        title: "Carlton、Fitzroy 和老修道院",
        items: [
          {
            id: "au-d8-reb",
            time: "10:30",
            kind: "sight",
            name: "皇家展览馆和卡尔顿花园",
            address: "9 Nicholson Street, Carlton VIC",
            lat: -37.8047,
            lng: 144.9717,
            reservation: "none",
            reservationNote: "花园和建筑外面免费。旁边的墨尔本博物馆要票，想进再买。",
            bookingUrl: "",
            why: "世界遗产建筑，周三上午人很少。从这里走路就进 Fitzroy。",
            photo: photo("au-d8-reb"),
            note: "走到 Bourke Street 坐 86 或 96 路电车往东，到 11 号站 Melbourne Museum 下，走五分钟。绕建筑和喷泉走一圈就够。"
          },
          {
            id: "au-d8-fitzroy",
            time: "11:30",
            kind: "sight",
            name: "Fitzroy 的 Gertrude Street 和后街",
            address: "Gertrude Street, Fitzroy VIC",
            lat: -37.806,
            lng: 144.981,
            reservation: "none",
            reservationNote: "街区，不用票。午饭在这条街上现场找。",
            bookingUrl: "",
            why: "本地人推荐的老街区。主街后面的 Rose Street、Kerr Street 一带是老排屋、小画廊和涂鸦，游客少。",
            photo: photo("au-d8-fitzroy"),
            note: "从花园东边过 Nicholson Street 就是 Gertrude Street。顺着往东走，看到喜欢的就拐进北边的小街。午饭在 Gertrude Street 或 Smith Street 吃，不用订。"
          },
          {
            id: "au-d8-convent",
            time: "14:00",
            kind: "sight",
            name: "Abbotsford Convent 老修道院",
            address: "1 St Heliers Street, Abbotsford VIC",
            lat: -37.8025,
            lng: 145.0036,
            reservation: "none",
            reservationNote: "园区免费进。",
            bookingUrl: "",
            why: "旧修道院改成的艺术园区，有草地、咖啡馆和亚拉河边步道，几乎没有旅行团。",
            photo: photo("au-d8-convent"),
            note: "从 Fitzroy 往北走到 Johnston Street，坐 200 或 207 路公交往东，Clarke Street 站下，走三到五分钟。不想等车就打车，十分钟左右。回城走 10 到 15 分钟到 Victoria Park 火车站，坐 Mernda 或 Hurstbridge 线进城。如果国际航班在下午，这一站取消，吃完午饭直接回城。"
          },
          {
            id: "au-d8-ngv",
            time: "下雨再去",
            kind: "sight",
            name: "维多利亚国家美术馆",
            address: "180 St Kilda Road, Melbourne",
            lat: -37.8226,
            lng: 144.9689,
            reservation: "none",
            reservationNote: "常设展免费，直接进。特展才要票。",
            bookingUrl: "https://www.ngv.vic.gov.au/whats-on/",
            why: "下雨的备选。周三白天人不多，常设展免费。",
            photo: photo("au-d8-ngv"),
            note: "下雨就把 Fitzroy 和修道院换成这里。从弗林德斯街沿圣基尔达路往南坐电车，有 Arts Precinct 或 NGV 字样的站下。"
          },
          {
            id: "au-d8-air",
            time: "回程",
            kind: "transport",
            name: "南十字坐 SkyBus 去机场",
            address: "Southern Cross Station",
            lat: -37.8184,
            lng: 144.9525,
            reservation: "none",
            reservationNote: "当天买票即可。",
            bookingUrl: "https://www.skybus.com.au/",
            note: "车站里跟着 SkyBus 牌子走。国际航班留三小时。大巴大约 30 到 40 分钟，傍晚可能堵。"
          }
        ]
      }
    ]
  }
];
